kind = "web"
previewPath = "/"
title = "La'maan London"
version = "1.0.0"
id = "artifacts/lamaan-london"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19546

[services.development]
run = "pnpm --filter @workspace/lamaan-london run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lamaan-london", "run", "build" ]
run = "pnpm --filter @workspace/lamaan-london run start"

[services.env]
PORT = "19546"
