// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/product-video": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/returns-shipping": {
    params: {};
  };
  "/scent-quiz": {
    params: {};
  };
  "/terms-of-service": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cart" | "/collections" | "/products/:handle" | "/product-video" | "/privacy-policy" | "/returns-shipping" | "/scent-quiz" | "/terms-of-service" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/collections.tsx": {
    id: "routes/collections";
    page: "/collections";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/product-video.tsx": {
    id: "routes/product-video";
    page: "/product-video";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/returns-shipping.tsx": {
    id: "routes/returns-shipping";
    page: "/returns-shipping";
  };
  "routes/scent-quiz.tsx": {
    id: "routes/scent-quiz";
    page: "/scent-quiz";
  };
  "routes/terms-of-service.tsx": {
    id: "routes/terms-of-service";
    page: "/terms-of-service";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/collections": typeof import("./app/routes/collections.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/product-video": typeof import("./app/routes/product-video.tsx");
  "routes/privacy-policy": typeof import("./app/routes/privacy-policy.tsx");
  "routes/returns-shipping": typeof import("./app/routes/returns-shipping.tsx");
  "routes/scent-quiz": typeof import("./app/routes/scent-quiz.tsx");
  "routes/terms-of-service": typeof import("./app/routes/terms-of-service.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};